[project]
name = "nvidia-repo-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.13.2",
    "fastapi>=0.129.2",
    "gitpython>=3.1.46",
    "langchain>=1.2.10",
    "langchain-chroma>=1.1.0",
    "langchain-classic>=1.0.1",
    "langchain-community>=0.4.1",
    "langchain-neo4j>=0.8.0",
    "langchain-nvidia-ai-endpoints>=1.0.4",
    "neo4j>=6.1.0",
    "openai>=2.21.0",
    "python-dotenv>=1.2.1",
]
